//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balance
    {
        public int LedgerId { get; set; }
        public int UserId { get; set; }
        public decimal CurrentBalance { get; set; }
    
        public virtual Ledger Ledger { get; set; }
        public virtual User User { get; set; }
    }
}
