//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Description
    {
        public int ObjectTypeId { get; set; }
        public int ObjectId { get; set; }
        public int SortOrder { get; set; }
        public string Title { get; set; }
        public string TextBody { get; set; }
        public bool IsHTML { get; set; }
    
        public virtual ObjectType ObjectType { get; set; }
    }
}
