//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrawOption
    {
        public int DrawId { get; set; }
        public int MaxEntriesPerUser { get; set; }
        public int EntriesToDraw { get; set; }
        public bool RemoveDrawnEntries { get; set; }
        public bool RemoveDrawnUsers { get; set; }
        public Nullable<int> NextDrawId { get; set; }
        public bool PassDrawnToNext { get; set; }
    
        public virtual Draw Draw { get; set; }
        public virtual Draw NextDraw { get; set; }
    }
}
