//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrawResult
    {
        public int DrawId { get; set; }
        public int DrawCount { get; set; }
        public int EntryId { get; set; }
        public System.DateTime DrawnDateTime { get; set; }
    
        public virtual DrawEntry DrawEntry { get; set; }
        public virtual Draw Draw { get; set; }
    }
}
