//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Draw
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Draw()
        {
            this.DrawEntries = new HashSet<DrawEntry>();
            this.DrawOptions = new HashSet<DrawOption>();
            this.DrawResults = new HashSet<DrawResult>();
            this.PendingTransactions = new HashSet<PendingTransaction>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int DrawId { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public int DrawTypeId { get; set; }
        public string Results { get; set; }
        public string DrawCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrawEntry> DrawEntries { get; set; }
        public virtual DrawOption DrawOption { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrawOption> DrawOptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrawResult> DrawResults { get; set; }
        public virtual DrawType DrawType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PendingTransaction> PendingTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
