//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupInvite
    {
        public int GroupId { get; set; }
        public string EmailAddress { get; set; }
        public System.DateTime LastInviteDate { get; set; }
        public int InviteCount { get; set; }
    
        public virtual Group Group { get; set; }
    }
}
