//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int ScheduleId { get; set; }
        public int DrawTypeId { get; set; }
        public int DayOfWeek { get; set; }
        public System.TimeSpan Time { get; set; }
    
        public virtual DrawType DrawType { get; set; }
    }
}
