//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDrawTypeOption
    {
        public int UserId { get; set; }
        public int DrawTypeId { get; set; }
        public bool PlayAll { get; set; }
        public int MaxPlay { get; set; }
        public int Priority { get; set; }
        public bool IsApproved { get; set; }
    
        public virtual DrawType DrawType { get; set; }
        public virtual User User { get; set; }
    }
}
