//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VerificationKey
    {
        public int VerificationId { get; set; }
        public int UserId { get; set; }
        public string EmailAddress { get; set; }
        public string VKey { get; set; }
        public Nullable<System.DateTime> SentOn { get; set; }
        public Nullable<System.DateTime> VerifiedOn { get; set; }
    
        public virtual User User { get; set; }
    }
}
